{% set name = "kguiaddons" %}
{% set version = "5.69.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kguiaddons-{{ version }}.tar.xz
  sha256: ff183277808d8884cdd30843d534ff554724efda688a6b26fbc58fc28c18cfc0

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kguiaddons', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - xorg-libx11
    - qt
  run:
    - xorg-libx11

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5GuiAddons.so

about:
  home: https://api.kde.org/frameworks/kguiaddons/html/index.html
  license: GPL-v2
  license_family: GPL
  license_file: COPYING
  summary: Utilities for graphical user interfaces
  description: |
    The KDE GUI addons provide utilities for graphical user interfaces
    in the areas of colors, fonts, text, images, keyboard input.
  doc_url: https://api.kde.org/frameworks/karchive/html/index.html
  dev_url: https://cgit.kde.org/kguiaddons.git/tree

extra:
  recipe-maintainers:
    - scopatz
